import * as React from 'react';
import ChartBuilder from '../shared/ChartBuilder';


export default class ProfileManagementStatistics extends React.Component<any, any> {

    render() {

        let values: any[] = [
            { label: '25', value: 20 },
            { label: '26', value: 40 },
            { label: '27', value: 10 },
            { label: '28', value: 20 },
            { label: '29', value: 30 },
            { label: '30', value: 95 },
            { label: '01', value: 90 },
            { label: '02', value: 60 },
            { label: '03', value: 80 } ,
            { label: '04', value: 80 },
            { label: '05', value: 60 },
            { label: '05', value: 60 },
            { label: '05', value: 30 },
            { label: '05', value: 50 },
            { label: '05', value: 80 },
            { label: '05', value: 85 },
            { label: '05', value: 86 },
            { label: '05', value: 88 },
            { label: '05', value: 90 },
            { label: '05', value: 96 },
            { label: '05', value: 99 },
            { label: '05', value: 95 },
            { label: '05', value: 95 },
            { label: '05', value: 100 },
            { label: '05', value: 62 },
            { label: '05', value: 80 },
            { label: '05', value: 87 },
            { label: '05', value: 90 },
            { label: '25', value: 20 },
            { label: '26', value: 40 },
            { label: '27', value: 10 },
            { label: '28', value: 20 },
            { label: '29', value: 30 },
            { label: '30', value: 95 },
            { label: '01', value: 90 },
            { label: '02', value: 60 },
            { label: '03', value: 80 } ,
            { label: '04', value: 80 },
            { label: '05', value: 60 },
            { label: '05', value: 60 },
            { label: '05', value: 30 },
            { label: '05', value: 50 },
            { label: '05', value: 80 },
            { label: '05', value: 85 },
            { label: '05', value: 86 },
            { label: '05', value: 88 },
            { label: '05', value: 90 },
            { label: '05', value: 96 },
            { label: '05', value: 99 },
            { label: '05', value: 95 },
            { label: '05', value: 95 },
            { label: '05', value: 100 },
            { label: '05', value: 62 },
            { label: '05', value: 80 },
            { label: '05', value: 87 },
            { label: '05', value: 90 },
            { label: '25', value: 20 },
            { label: '26', value: 40 },
            { label: '27', value: 10 },
            { label: '28', value: 20 },
            { label: '29', value: 30 },
            { label: '30', value: 95 },
            { label: '01', value: 90 },
            { label: '02', value: 60 },
            { label: '03', value: 80 } ,
            { label: '04', value: 80 },
            { label: '05', value: 60 },
            { label: '05', value: 60 },
            { label: '05', value: 30 },
            { label: '05', value: 50 },
            { label: '05', value: 80 },
            { label: '05', value: 85 },
            { label: '05', value: 86 },
            { label: '05', value: 88 },
            { label: '05', value: 90 },
            { label: '05', value: 96 },
            { label: '05', value: 99 },
            { label: '05', value: 95 },
            { label: '05', value: 95 },
            { label: '05', value: 100 },
            { label: '05', value: 62 },
            { label: '05', value: 80 },
            { label: '05', value: 87 },
            { label: '05', value: 90 },
            { label: '25', value: 20 },
            { label: '26', value: 40 },
            { label: '27', value: 10 },
            { label: '28', value: 20 },
            { label: '29', value: 30 },
            { label: '30', value: 95 },
            { label: '01', value: 90 },
            { label: '02', value: 60 },
            { label: '03', value: 80 } ,
            { label: '04', value: 80 },
            { label: '05', value: 60 },
            { label: '05', value: 60 },
            { label: '05', value: 30 },
            { label: '05', value: 50 },
            { label: '05', value: 80 },
            { label: '05', value: 85 },
            { label: '05', value: 86 },
            { label: '05', value: 88 },
            { label: '05', value: 90 },
            { label: '05', value: 96 },
            { label: '05', value: 99 },
            { label: '05', value: 95 },
            { label: '05', value: 95 },
            { label: '05', value: 100 },
            { label: '05', value: 62 },
        ];

        return (
            <div style={{paddingTop: '20px'}}>

                <ChartBuilder values={values} />
            </div>)
    }
}